server:
  port: 0

cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.testcbrcursondateadapter.cbr.wsdl'

adapter:
  uri: 'http://localhost:8080'

rabbitmq:
  exchange:
    history: change-history-exchange
    logging: logging-exchange
  routingkey:
    history: change-history-routingkey
    logging: logging-routingkey
  queue:
    history: change-history-queue
    logging: logging-queue